### ISSUE TITLE
Import naming convention

### ISSUE THREAD

**Issue by anacrolix** [libp2p/go-libp2p#524] opened 2019-01-23 23:12 UTC
The import naming convention in use in the Go packages is not idiomatic.
```
	u "github.com/ipfs/go-ipfs-util"
	peer "github.com/libp2p/go-libp2p-peer"
	pstore "github.com/libp2p/go-libp2p-peerstore"
	routing "github.com/libp2p/go-libp2p-routing"
```
In this example, `routing`, and `peer` are automatically inferred to be those names anyway. `go-libp2p-peerstore` should probably have its package renamed to `pstore` (`package pstore`) for import purposes, if such a name is intended to be the convention.

I propose that explicitly naming imports be stopped from this point onwards, and that go repositories be appropriately named, or use the intended package clause.

**Comment by raulk** [comment] 2019-01-23 23:14
I agree. I’d like to understand if these are deliberate choices for e.g. historical reasons, or if these mismatches were unintentional.

**Comment by anacrolix** [comment] 2019-01-25 00:03
> We don't want upstream package name changes to break things for us.

That won't happen because versioning. If something more fragile like go get is being used, there are plenty of other things more likely to break that don't require deviating from conventions.

> I'd just try to switch to "peerstore" everywhere. That's also quite a bit more descriptive than "pstore" (which was mostly used due to laziness).

I think just let the user decide. Go's formatting tools are already very good at deciding when to explicitly add the name.

**Comment by Stebalien** [comment] 2019-01-25 15:19
I forgot the most important one: package names can be non-obvious (e.g., most of our packages). I can have:

```go
package main

import "github.com/foo/bar"

func main() {
    baz.Run()
}
```

IIRC, this was our original motivation for explicitly naming imports (the decision was made long before I joined).

> That won't happen because versioning.

That's still breaking. A breaking change is one that requires manual intervention when updating. There *are* good reasons to make breaking changes but a small aesthetic fix isn't one of them.

> I think just let the user decide. Go's formatting tools are already very good at deciding when to explicitly add the name.

That's fine. Users can call name this package however they'd like. However, the point of this issue was to try to make this consistent within our projects, hence the proposal.

**Comment by anacrolix** [comment] 2019-02-10 21:06
Some token [appeal to authority](https://github.com/golang/go/wiki/CodeReviewComments#imports).

**Comment by Stebalien** [comment] 2019-02-10 23:46
I've read that document. Unfortunately, quite a few of our packages (and other packages we depend on) wouldn't qualify as "good" by that standard. Changing this now would be a massively breaking change for a tiny (apparently arbitrary) style issue.

**Comment by schomatis** [comment] 2019-02-11 04:38
This seems like a duplicate of https://github.com/ipfs/go-ipfs/issues/5056.

**Closed** 2021-07-22 23:36 UTC
