### ISSUE TITLE
I use quic transmission，but sometimes quic will close all network connections.

### ISSUE THREAD

**Issue by s1377427321** [libp2p/go-libp2p#519] opened 2019-01-12 03:49 UTC
source code：
ts, err := c.conn.AcceptStream()

i detecte error
InternalError: read udp4 0.0.0.0:55289: wsarecvfrom: The connection has been broken due to keep-alive activity detecting a failure while the operation was in progress

**Comment by marten-seemann** [comment] 2019-01-23 09:11
We had an issue for this in quic-go: https://github.com/lucas-clemente/quic-go/issues/1737. Being pretty inexperienced with Windows, I assumed that wsarecvfrom was some an error code of another library wrapped around quic-go, which is why I closed this issue without action, and unfortunately never got any response.
I'm running all unit and some of the integration tests on AppVeyor on Windows, and everything seems to work fine there. I'll need some guidance in how to reproduce this issue.

**Comment by anacrolix** [comment] 2019-01-24 04:12
I think the following could help:

- https://github.com/anacrolix/go-libutp/blob/83b91757267c217d24927a1cec0a57f2ea75a797/socket.go#L141
- https://github.com/anacrolix/torrent/issues/83

**Comment by Stebalien** [comment] 2019-01-24 13:59
@djdv, any ideas?

**Comment by djdv** [comment] 2019-01-24 14:45
Disclaimer: I lack experience with UDP on Windows. Mostly familiar with TCP and Named Pipe connections.

This appears to be 
WSAECONNRESET (10052)
https://docs.microsoft.com/en-us/windows/desktop/WinSock/windows-sockets-error-codes-2
MSDN also says this about the error in reference to UDP specifically.
>The virtual circuit was reset by the remote side executing a hard or abortive close. The application should close the socket as it is no longer usable. For a UPD datagram socket, this error would indicate that a previous send operation resulted in an ICMP "Port Unreachable" message. 

I'm lacking context here though. I wouldn't expect this to happen when listening alone, but I would expect that during an accept or send. Probably in the case where data was buffered, the host became unreachable, and the next read call errors.

With context from @anacrolix it looks like we can receive innocuous or potentially incorrect (library fault) errors from Read() that are probably tripping something to close the socket prematurely. In the linked torrent issue it seems appropriate to disregard the error entirely or adjust the buffers (depending on what error was actually received.

My best guess is that we need to explode these errors out and switch on them using 
https://docs.microsoft.com/en-us/windows/desktop/api/winsock2/nf-winsock2-wsarecvfrom
as a reference.

**Comment by anacrolix** [comment] 2019-01-25 00:00
> With context from @anacrolix it looks like we can receive innocuous or potentially incorrect (library fault) errors from Read() that are probably tripping something to close the socket prematurely. In the linked torrent issue it seems appropriate to disregard the error entirely or adjust the buffers (depending on what error was actually received.

Yep, spot on.

> My best guess is that if these errors aren't already exposed, we need to explode them out and switch on them

I'd love to see how you solve that. It's difficult to pin down specific errors in Go due to the very loose typing inside the error interface.

**Comment by djdv** [comment] 2019-01-25 18:25
>I'd love to see how you solve that. It's difficult to pin down specific errors in Go due to the very loose typing inside the error interface.

It's true. Go can make this pretty ugly if the libs don't export error variables for us.
Typically you have to do some digging to find the origin of the error.

In this case it likely originates from `pkg/net` and is likely a `net.OpError`.
If we had a reproducible case we could easily just use Go itself to tell us the underlying type with a simple fmt call `fmt.Printf("%T %#v\n", err, err)`. 

Once we know the source and concrete type of the error, it's just a matter of unwrapping it. It's messy but likely necessary if the abstractions don't already provide a way to do something like `err == somelib.ErrUDPTTL`

``` go
err := ambigousErr()
if netErr, ok := err.(net.OpError); ok {
    if netErr.Temporary() {
        // drop err
    }
    log.Errorf("Unexpected/Unhandled error: {%T}%#v", netErr.Err, netErr.Err)
}
```

Depending on the source of the error and the level of control needed, you could repeat the pattern to continue unwrapping. In the case of a `net.OpError` you could get the underlying error from the struct which is likely in itself a `syscall.Errno` or a wrapper of it.
``` go
...
if netErr.Temporary() {
    // drop err
}
if platformErr, ok := netErr.Err.(syscall.Errno); ok {
    if platformErr == SomeConst {
    // drop it
    }
log.Errorf("Unexpected/Unhandled error: {%T}%#v", netErr.Err, netErr.Err)
}
```

**Comment by djdv** [comment] 2019-01-25 18:46
It's looking like the error is generated here:
https://golang.org/src/net/fd_windows.go#L160
``` go
func (fd *netFD) readFrom(buf []byte) (int, syscall.Sockaddr, error) {
	n, sa, err := fd.pfd.ReadFrom(buf)
	runtime.KeepAlive(fd)
	return n, sa, wrapSyscallError("wsarecvfrom", err)
}
```
https://golang.org/src/net/error_posix.go

If needed you could insert this into one of them to see the whole call stack and see who's generating this error when it happens.
``` go
var i int
for {
	pc, fn, line, ok := runtime.Caller(i)
	if !ok {
		break
	}
	fmt.Printf("[%d] %s[%s:%d]\n", i, runtime.FuncForPC(pc).Name(), fn, line)
	i++
}
```

**Comment by Stebalien** [comment] 2021-07-22 23:38
Closing in favor of https://github.com/lucas-clemente/quic-go/issues/1737.

**Closed by Stebalien** 2021-07-22 23:38 UTC
Labels: status/blocked
