### ISSUE TITLE
Slight refactor of auto-relay interfaces

### ISSUE THREAD

**Issue by mgoelzer** [libp2p/go-libp2p#471] opened 2018-11-05 19:30 UTC
Following some synchronous discussion in the libp2p bi-weekly meeting today, resolved:

- https://github.com/libp2p/go-libp2p/pull/454 is good to merge 🍾
- Ideally, interfaces that may change should be marked as `unstable` in that PR
- @vyzo, @Stebalien and @bigs should immediately figure out how to refactor interfaces before users start relying on them.  Two main areas:
  - push identify method
  - revise the identify service to push new addresses

I'll let you all discuss these matters here.  Marking as high priority so that it does not get forgotten. 😀

**Comment by raulk** [comment] 2018-11-05 22:19
Closing as this is a duplicate of #472 – the latter of which is tagged and all.

**Closed by raulk** 2018-11-05 22:19 UTC
