### ISSUE TITLE
Messages Concatenated Unexpectedly 

### ISSUE THREAD

**Issue by ericxtang** [libp2p/go-libp2p#250] opened 2017-12-01 06:35 UTC
Hi,

I've been noticing sometimes my messages get dropped.  After some digging, I realized when messages get sent too closely together, sometimes they get concatenated into a single message (msg1 and msg2 get turned into msg1msg2).  This is a problem because the multicodec unmarshalling ignores one of the messages.  

I've written [2 examples](https://github.com/ericxtang/go-libp2p/blob/master/examples/race/race.go) to illustrate this issue.  

In `race1()`, you will see the messages getting concatenated like this:
```
Got message: 01
Got message: 23
Got message: 45
Got message: 6
Got message: 7
Got message: 89
Got message: 1011
Got message: 1213
Got message: 14
Got message: 15
Got message: 16
Got message: 1718
Got message: 19
```

In `race2()`, you'll see messages getting dropped:

```
Got message: 0
Got message: 2
Got message: 4
Got message: 5
Got message: 7
Got message: 9
Got message: 10
Got message: 12
Got message: 16
Got message: 18
```

I could try and do the unmarshalling manually, but the data off the wire is encrypted because I'm using encrypted connections, and I'm not quite sure how to decrypt it manually.
```
got /json
{"Op":0,"Data":"Of+BAwEBDVN0cmVhbURhdGFNc2cB/4IAAQMBBVNlcU5vAQYAAQZTdHJtSUQBDAABBERhdGEBCgAAAAb/ggMBMAA="}

got /json
{"Op":0,"Data":"Of+BAwEBDVN0cmVhbURhdGFNc2cB/4IAAQMBBVNlcU5vAQYAAQZTdHJtSUQBDAABBERhdGEBCgAAAAb/ggMBMQA="}
/json
{"Op":0,"Data":"Of+BAwEBDVN0cmVhbURhdGFNc2cB/4IAAQMBBVNlcU5vAQYAAQZTdHJtSUQBDAABBERhdGEBCgAAAAb/ggMBMgA="}
```

Anything I can do to make sure the messages aren't concatenated?

**Comment by Stebalien** [comment] 2017-12-01 20:57
Not a bug. Continued on https://discuss.ipfs.io/t/go-libp2p-messages-concatenated-unexpectedly/1543.

**Comment by Stebalien** [comment] 2017-12-01 21:03
Actually, that second example looks like it should work. This may be a bug in go-multicodec.

**Comment by Stebalien** [comment] 2017-12-01 21:15
Yes, this is a bug in go-multicodec. If you pass `true` instead of `false` to `mcjson.Multicodec` it should work but we need to fix this anyways.

See https://github.com/multiformats/go-multicodec/issues/24

**Comment by kevina** [comment] 2017-12-01 22:19
@Stebalien should we keep this open until multiformats/go-multicodec#24 is fixed?

**Comment by Stebalien** [comment] 2017-12-01 22:39
This isn't really a bug in go-libp2p.

**Comment by Stebalien** [comment] 2017-12-01 22:59
Reopening because this does affect the protocol-multiplexing-with-multicodecs example.

**Comment by Stebalien** [comment] 2021-07-22 23:26
Fixed by deprecating the library. There was no good way to fix this.

**Closed by Stebalien** 2021-07-22 23:26 UTC
