### ISSUE TITLE
identify: flaky TestLargeIdentifyMessage

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#1523] opened 2022-05-24 14:01 UTC
```
  === RUN   TestLargeIdentifyMessage
      id_test.go:845: test peer1 has peer2 addrs correctly
      id_test.go:860: test peer2 has peer1 addrs correctly
      id_test.go:873: testing addrs just after disconnect
      id_test.go:876: 
          	Error Trace:	id_test.go:41
          	            				id_test.go:876
          	Error:      	elements differ
          	            	
          	            	extra elements in list A:
          	            	([]interface {}) (len=2) {
          	            	 (*multiaddr.multiaddr)({
          	            	  bytes: ([]uint8) (len=8) {
          	            	   00000000  04 7f 00 00 01 06 c3 e4                           |........|
          	            	  }
          	            	 }),
          	            	 (*multiaddr.multiaddr)({
          	            	  bytes: ([]uint8) (len=11) {
          	            	   00000000  04 7f 00 00 01 91 02 ed  e9 cc 03                 |...........|
          	            	  }
          	            	 })
          	            	}
          	            	
          	            	
          	            	listA:
          	            	([]multiaddr.Multiaddr) (len=2) {
          	            	 (*multiaddr.multiaddr)({
          	            	  bytes: ([]uint8) (len=8) {
          	            	   00000000  04 7f 00 00 01 06 c3 e4                           |........|
          	            	  }
          	            	 }),
          	            	 (*multiaddr.multiaddr)({
          	            	  bytes: ([]uint8) (len=11) {
          	            	   00000000  04 7f 00 00 01 91 02 ed  e9 cc 03                 |...........|
          	            	  }
          	            	 })
          	            	}
          	            	
          	            	
          	            	listB:
          	            	([]multiaddr.Multiaddr) {
          	            	}
          	Test:       	TestLargeIdentifyMessage
          	Messages:   	QmTYuoLmQHu34jyaN9ywjFA7r1bQLaapYZTddoRupT1ENg did not have addr for QmQ81pQuehk4dRkwkDGRrqpvQ4Ga6hZqzTkydGE3S1KkWG
      id_test.go:877: peerstore has no signed record for peer QmQ81pQuehk4dRkwkDGRrqpvQ4Ga6hZqzTkydGE3S1KkWG
  --- FAIL: TestLargeIdentifyMessage (9.11s)

**Comment by marten-seemann** [comment] 2022-06-01 11:14
Failed run: https://github.com/libp2p/go-libp2p/runs/6681155403?check_suite_focus=true

**Comment by MarcoPolo** [comment] 2022-06-02 20:31
Re openeing since I think there are some fixes still left to do

**Comment by schomatis** [comment] 2022-06-24 15:08
Picking this up as related to (or maybe duplicate of) https://github.com/libp2p/go-libp2p/issues/1164.

**Closed** 2023-02-08 22:44 UTC
Labels: kind/bug
