### ISSUE TITLE
TestReuseGarbageCollect is flaky

### ISSUE THREAD

**Issue by julian88110** [libp2p/go-libp2p#1787] opened 2022-09-29 19:11 UTC
Sometimes fails on Windows platform.  (go 1.18.x)

  === RUN   TestReuseGarbageCollect
      reuse_test.go:174: 
          	Error Trace:	D:\a\go-libp2p\go-libp2p\p2p\transport\quic\reuse_test.go:174
          	Error:      	Condition never satisfied
          	Test:       	TestReuseGarbageCollect
  --- FAIL: TestReuseGarbageCollect (0.55s)

<details>
<summary>Version Information</summary>
v0.23.2 
<pre>

</pre>
</details>

**Comment by marten-seemann** [comment] 2022-10-08 10:43
Duplicate of #1682.

**Closed by marten-seemann** 2022-10-08 10:43 UTC
