### ISSUE TITLE
Why didn't you provide the method of getting external IP address?

### ISSUE THREAD

**Issue by hyunsooda** [libp2p/go-libp2p#722] opened 2019-09-14 09:35 UTC
I have a long time to find a method that can query peer's external IP address, but I didn't find that method.
So, I used this code to see peer's public IP. why your library doesn't provide this or where is it if it exists?

```
	url := "https://api.ipify.org?format=text"
	resp, err := http.Get(url)
	defer resp.Body.Close()
	ip, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		panic(err)
	}
	fmt.Printf("My IP is:%s\n", ip)
```

**Comment by upperwal** [comment] 2019-09-14 13:53
You can find all addresses associated with your node with `host.Addrs()`

**Comment by hyunsooda** [comment] 2019-09-14 15:37
host.Addrs() is not shown the external address if I use router.
I think that my question has wrong points where seems related to UPnP, Port Forwarding, etc. 
Anyway, thanks for answer. have a nice day.

**Comment by upperwal** [comment] 2019-09-14 15:54
How many nodes are there in your network?

Libp2p has a condition that an external address is only accepted by a local peer if > 3 peers observed that address.

If you are testing with a few nodes (2 or 3). Your external address will never be accepted and hence not available in `host.Addrs()`. 

What to do:
1. Try spawning more nodes or
2. Change the value of `ActivationThresh` to 1 for development.

**Comment by hyunsooda** [comment] 2019-09-14 16:25
What's your mean..?
First of all, I followed your instruction that I have to create more nodes.
```
func main() {
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	h, err := libp2p.New(ctx)
	if err != nil {
		panic(err)
	}
	h2, _ := libp2p.New(ctx)
	h3, _ := libp2p.New(ctx)
	h4, _ := libp2p.New(ctx)

	fmt.Println(h2, h3, h4)
	fmt.Printf("IP is %s\n", h2.Addrs())
}
```
In this code, I have 4 nodes but output is internal IP, not external.

**Comment by upperwal** [comment] 2019-09-14 16:35
All these nodes are running locally (LAN) and no traffic flows on the internet. 

Spin up a few nodes on some cloud service (public IP with open ports) and try connecting with them. You will see the external IPs.

**Comment by hyunsooda** [comment] 2019-09-14 18:07
It doesn't show external IP. I have set port forwarding(8881,8882,8883,8884) and tested. but it shows internal IP continually.
```
func main() {
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	h1, _ := libp2p.New(ctx, libp2p.ListenAddrStrings("/ip4/0.0.0.0/tcp/8884"))
	h2, _ := libp2p.New(ctx, libp2p.ListenAddrStrings("/ip4/0.0.0.0/tcp/8881"))
	h3, _ := libp2p.New(ctx, libp2p.ListenAddrStrings("/ip4/0.0.0.0/tcp/8882"))
	h4, _ := libp2p.New(ctx, libp2p.ListenAddrStrings("/ip4/0.0.0.0/tcp/8883"))

	h1peerInfo := &peerstore.PeerInfo{
		ID:    h1.ID(),
		Addrs: h1.Addrs(),
	}
	h2peerInfo := &peerstore.PeerInfo{
		ID:    h2.ID(),
		Addrs: h2.Addrs(),
	}
	h3peerInfo := &peerstore.PeerInfo{
		ID:    h3.ID(),
		Addrs: h3.Addrs(),
	}
	h4peerInfo := &peerstore.PeerInfo{
		ID:    h4.ID(),
		Addrs: h4.Addrs(),
	}

	h1addr, _ := peerstore.InfoToP2pAddrs(h1peerInfo)
	h2addr, _ := peerstore.InfoToP2pAddrs(h2peerInfo)
	h3addr, _ := peerstore.InfoToP2pAddrs(h3peerInfo)
	h4addr, _ := peerstore.InfoToP2pAddrs(h4peerInfo)

	h1multiaddr, _ := multiaddr.NewMultiaddr(fmt.Sprintf("%s", h1addr[0]))
	h2multiaddr, _ := multiaddr.NewMultiaddr(fmt.Sprintf("%s", h2addr[0]))
	h3multiaddr, _ := multiaddr.NewMultiaddr(fmt.Sprintf("%s", h3addr[0]))
	h4multiaddr, _ := multiaddr.NewMultiaddr(fmt.Sprintf("%s", h4addr[0]))

	h1peer, _ := peerstore.InfoFromP2pAddr(h1multiaddr)
	h2peer, _ := peerstore.InfoFromP2pAddr(h2multiaddr)
	h3peer, _ := peerstore.InfoFromP2pAddr(h3multiaddr)
	h4peer, _ := peerstore.InfoFromP2pAddr(h4multiaddr)

	if err := h1.Connect(ctx, *h2peer); err != nil {
		panic(err)
	}
	if err := h1.Connect(ctx, *h3peer); err != nil {
		panic(err)
	}
	if err := h1.Connect(ctx, *h4peer); err != nil {
		panic(err)
	}

	if err := h2.Connect(ctx, *h1peer); err != nil {
		panic(err)
	}
	if err := h2.Connect(ctx, *h3peer); err != nil {
		panic(err)
	}
	if err := h2.Connect(ctx, *h4peer); err != nil {
		panic(err)
	}

	if err := h3.Connect(ctx, *h1peer); err != nil {
		panic(err)
	}
	if err := h3.Connect(ctx, *h2peer); err != nil {
		panic(err)
	}
	if err := h3.Connect(ctx, *h4peer); err != nil {
		panic(err)
	}

	if err := h4.Connect(ctx, *h1peer); err != nil {
		panic(err)
	}
	if err := h4.Connect(ctx, *h2peer); err != nil {
		panic(err)
	}
	if err := h4.Connect(ctx, *h3peer); err != nil {
		panic(err)
	}

	for {
		fmt.Println("my ip ", h1.Addrs())
		fmt.Println("my ip ", h2.Addrs())
		fmt.Println("my ip ", h3.Addrs())
		fmt.Println("my ip ", h4.Addrs())
	}
}
```

**Comment by upperwal** [comment] 2019-09-15 17:31
This configuration is still local. You need to create multiple hosts in different instances and connect them with each other.

**Comment by hyunsooda** [comment] 2019-09-17 18:05
Okay, thanks :)
I have last question; You said that Libp2p has a condition that an external address is only accepted by a local peer if > 3 peers.

Why you made such a policy and what has the meaning?
Where can I see the code in the Libp2p?

**Comment by upperwal** [comment] 2019-09-17 19:02
I have not contributed to this code so just guessing.

This could have been done to make sure that the observed IP has not been changed within a given TTL. More random peers see you at a given IP within a timeframe there is a high probability that someone can reach you at that IP address.

Here is the code:
https://github.com/libp2p/go-libp2p/blob/02e6218268f8b3aa6452790c8f698e51bfa00d6a/p2p/protocol/identify/obsaddr.go#L34-L38

Look for the usage of `activated` function.

*This might become configurable or dynamic in the future.*

**Comment by Stebalien** [comment] 2019-09-30 15:20
> Why you made such a policy and what has the meaning?

The issue isn't actually the IP, it's the port. We have a activation threshold to make sure our peers are observing a stable port number, not an ephemeral one.

**Comment by Stebalien** [comment] 2019-09-30 15:20
(closing as I believe this has been resolved)

**Closed by Stebalien** 2019-09-30 15:20 UTC

**Comment by upperwal** [comment] 2019-10-02 08:24
> We have a activation threshold to make sure our peers are observing a stable port number, not an ephemeral one.

yeah, make sense

**Comment by biswajitAqb** [comment] 2020-11-11 10:26
>     2. Change the value of `ActivationThresh` to 1 for development.

Can you please guide me how to override the number from 4 to 1 , actually I'm new to GO as well as LibP2P.
