### ISSUE TITLE
Testground tests for simultaneous connect

### ISSUE THREAD

**Issue by aarshkshah1992** [libp2p/go-libp2p#1056] opened 2021-02-17 12:28 UTC
For https://github.com/libp2p/go-libp2p/issues/1039.

We need to write testground plans that test backward compatibility of the simultaneous connect feature in multistream i.e. connections should work when a peer that does/does NOT support simultaneous connect tries to dial peer that does NOT/does support simultaneous connect.

1. Peer that does NOT support simultaneous connect should be able to connect to a peer that support simultaneous connect.
2. Opposite of 1.

**Comment by aarshkshah1992** [comment] 2021-02-17 12:29
cc @vyzo

**Comment by marten-seemann** [comment] 2021-12-14 09:51
Duplicate of #1022.

**Closed by marten-seemann** 2021-12-14 09:51 UTC
Labels: nat-traversal
