### ISSUE TITLE
Getting "(default failure)" when connecting to DHT bootstrap node

### ISSUE THREAD

**Issue by joosep-wm** [libp2p/go-libp2p#359] opened 2018-06-13 11:01 UTC
Hi

We are trying to build a p2p gossip system using libp2p pieces. For some reason we are not able to connect the DHT to any bootstrap node. I put together a small sample project that fails

Sample project: https://github.com/joosep-wm/connect-to-dht
All dependencies are latest from the master branch.

The error it produces:
> I0612 13:10:28.624082   60616 main.go:73] DHT self id: <peer.ID 12D3Ko> ([/ip4/0.0.0.0/tcp/9000])
> I0612 13:10:28.625911   60616 main.go:74] Connecting to : {<peer.ID aCpDMG> [/ip4/104.131.131.82/tcp/4001]}
> panic: dial attempt failed: failed to dial <peer.ID aCpDMG> (default failure)
> 
> goroutine 1 [running]:
> main.main()
>     /Users/joosep/GoTest1/src/github.com/joosep-wm/connect-to-dht/main.go:76 +0x4a8

Is it a bug or we are using it wrongly?

**Comment by bigs** [comment] 2018-06-13 17:45
@joosep-wm Thanks for making the issue. Curious about your project! After taking a surprisingly deep dive on this (ha!), I believe the issue is related to our recent transport refactor. Specifically, you should create the `Host` with the interface exposed in [go-libp2p](https://godoc.org/github.com/libp2p/go-libp2p). All of the default transports have been removed from `Swarm`. Creating the `Host` with `New` will take care of that for you! It also makes things like adding your peer identity and NAT manager much simpler.

The error you're seeing is the result of your swarm having no transports added. As a result, all of the peer addresses are filtered away during the dial process.

Let me know if this helps! If you'd like a simple example of how to use the `New` interface, take a look at [the echo example](https://github.com/libp2p/go-libp2p/blob/master/examples/echo/main.go).

**Comment by Stebalien** [comment] 2018-06-13 18:07
Hm. I'm going to add an error message for this case...

**Comment by Stebalien** [comment] 2018-06-13 18:18
Also, you'll need to tell libp2p to listen on some address. `addrsFactory` just tells libp2p which addresses it should announce.

**Comment by jvsteiner** [comment] 2018-06-14 08:41
@Stebalien - we had been using the `bhost.NewHost` constructor rather than the `libp2p.New`.  We switched to `NewHost` because for some reason I thought that the latter, if not exactly depreciated, was being held around for legacy reasons relating to ipfs.  whats the most future-proof choice?

**Comment by bigs** [comment] 2018-06-14 13:03
We just landed a pretty large refactor that cleans up the way we handle
transports. libp2p.New is the way to go moving forward.

**Comment by Stebalien** [comment] 2018-06-14 17:55
@jvsteiner you're thinking of `bhost.New` versus `bhost.NewHost`. `bhost.NewHost` is the correct way to construct a new host manually. However, if you want a libp2p node that "just works", use `libp2p.New` (from `github.com/libp2p/go-libp2p`).

Basically, in the refactor, we moved all the defaults, fallbacks, and other magic into the `libp2p.New` constructor.

**Comment by jvsteiner** [comment] 2018-06-15 09:39
@Stebalien indeed, you are correct, sir - much appreciated.  loving the new constructor, so much less painful!

**Comment by zhy842530698** [comment] 2021-05-26 16:07
i also  meet the same problems ,someone who tell me why  is the reason that failed to bootstrap. failed to dial : all dials failed?

**Comment by Stebalien** [comment] 2021-05-26 16:47
Likely due to firewalls. Please open a new topic in discuss.libp2p.io and include your libp2p version, etc.

(closing this issue as it was fixed ages ago)

**Closed by Stebalien** 2021-05-26 16:47 UTC
