### ISSUE TITLE
Staticcheck Should Be Considered For "All" Repository CI Processes

### ISSUE THREAD

**Issue by bonedaddy** [libp2p/go-libp2p#866] opened 2020-04-02 09:31 UTC
[staticcheck](https://staticcheck.io/) is a pretty awesome static analysis tool. It covers a wide variety of checks from simplification, missed error checks, overshadowed variables, etc... and it's also very configurable which means you can ignore lints you dont like. 

In particular the lints for missed error checks, overshadowed variables, defers before error checks, are pretty useful. From my own experience  it seems to lead to a healthier code base, and has identified on more than one occasion logic that would in edge cases cause bugs, as well as helping to figure out why a test was passing that shouldn't. 

Implementing them in **all** repositories is certainly a bit excessive, but the great thing about staticcheck is that it can be implemented without any disruptions or needing to consider breaking changes.

Starting to get pretty sleepy as I write this so I'll show a couple of the "superficial" lints performed.

```Go
	f := func(ctx context.Context, p peer.ID) bool {
		if p == candidate {
			return true
		}
		return false
	}
```

Which could be changed to

```Go
	f := func(ctx context.Context, p peer.ID) bool {
		return p == candidate
	}
```

Now in this particular case whether this is an improvement is ultimately up to you. It can also catch things like:

```Go
select {
case <-ctx.Done():
}
```

Which can be simplified into:

```Go
<-ctx.Done()
```

**Comment by marten-seemann** [comment] 2020-04-02 09:35
In quic-go, I'm using [GolangCI-Lint](https://github.com/golangci/golangci-lint). staticcheck can be run as part of that, in addition to a couple of other useful linters.

**Comment by Stebalien** [comment] 2020-04-03 04:04
I plan on slowly transitioning to CircleCI with https://circleci.com/orbs/registry/orb/ipfs/ci-go (we're doing the same in go-ipfs). That will give us:

* Cross platform builds (ensures we at least _build_ on all reasonable platforms).
* lints
* tests
* benchmark against master (kind of broken at the moment)

**Comment by raulk** [comment] 2020-05-12 12:46
We should adopt golangci-lint. Barring [memory usage regressions in v1.24](https://github.com/golangci/golangci-lint/issues/994), it has been fantastic on https://github.com/testground/testground/.

**Comment by raulk** [comment] 2020-05-12 12:46
CircleCI migration: #920.

**Comment by BigLep** [comment] 2021-03-29 15:25
Closing since we're moving to unified CI using GitHub Actions.

**Closed by BigLep** 2021-03-29 15:25 UTC
Labels: kind/enhancement
