### ISSUE TITLE
TestLocalhostAddrFilteirng failed

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#844] opened 2020-03-17 21:51 UTC
```
--- FAIL: TestLocalhostAddrFiltering (0.06s)

    id_test.go:268: expected one addr, found [/ip4/1.2.3.4/tcp/1234 /ip4/127.0.0.1/tcp/2345]
```

This one _shouldn't_ be timing related.

**Comment by marten-seemann** [comment] 2023-06-28 02:36
Duplicate of #854.

**Closed by marten-seemann** 2023-06-28 02:36 UTC
Labels: kind/bug
